# Generated by Django 2.2.2 on 2020-05-04 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default=True, max_length=30, verbose_name='ユーザー名')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=255, unique=True, verbose_name='password')),
                ('profile', models.CharField(blank=True, max_length=255, verbose_name='profile')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'アカウント',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(max_length=10, verbose_name='メッセージ内容')),
                ('target_id', models.CharField(max_length=10, verbose_name='送り先のID')),
                ('source_id', models.CharField(max_length=10, verbose_name='送り手のID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'メッセージ',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10, verbose_name='ニックネーム')),
                ('yorozuya_name', models.CharField(default='', max_length=10, verbose_name='万事屋の名前')),
                ('profile_image', models.ImageField(default='', upload_to='', verbose_name='プロフィール画像')),
                ('yorozu_main_image', models.ImageField(default='', upload_to='', verbose_name='万屋メイン画像')),
                ('profile_description', models.TextField(max_length=255, verbose_name='プロフィール説明')),
                ('review_score', models.IntegerField(verbose_name='レビュースコア')),
                ('twitter_account', models.CharField(blank=True, default='', max_length=80, verbose_name='twitterのアカウント')),
                ('instagram_account', models.CharField(blank=True, default='', max_length=80, verbose_name='instagramのアカウント')),
                ('facebook_account', models.CharField(blank=True, default='', max_length=80, verbose_name='facebookのアカウント')),
            ],
            options={
                'verbose_name_plural': 'プロフィール',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='プランタイトル')),
                ('description', models.TextField(max_length=255, verbose_name='プランの説明')),
                ('image', models.ImageField(default='', upload_to='', verbose_name='イメージ画像')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='料金')),
                ('tags', models.ManyToManyField(blank=True, to='yorozu.Tag')),
                ('yorozuya_profile', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='yorozu.Profile', verbose_name='作成者')),
            ],
            options={
                'verbose_name_plural': 'プラン',
            },
        ),
    ]
