# Generated by Django 2.2.2 on 2020-05-10 09:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=30, verbose_name='氏名')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='苗字(姓)')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='名前(名)')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=255, unique=True, verbose_name='パスワード')),
                ('is_active', models.BooleanField(default=True, verbose_name='ログイン状態')),
                ('is_staff', models.BooleanField(default=True, verbose_name='adminサイトのログイン権限')),
            ],
            options={
                'verbose_name_plural': 'アカウント',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('yorozu_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='YOROZU\x08 ID')),
                ('nickname', models.CharField(max_length=10, verbose_name='ニックネーム')),
                ('yorozuya_name', models.CharField(default='', max_length=10, verbose_name='万屋の名前')),
                ('profile_image', models.ImageField(default='', upload_to='', verbose_name='プロフィール画像')),
                ('yorozu_main_image', models.ImageField(default='', upload_to='', verbose_name='サムネ画像')),
                ('profile_description', models.TextField(max_length=255, verbose_name='プロフィール説明')),
                ('review_score', models.IntegerField(verbose_name='レビュースコア')),
                ('twitter_account', models.CharField(blank=True, default='', max_length=80, verbose_name='twitterのアカウント')),
                ('instagram_account', models.CharField(blank=True, default='', max_length=80, verbose_name='instagramのアカウント')),
                ('facebook_account', models.CharField(blank=True, default='', max_length=80, verbose_name='facebookのアカウント')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='アカウント情報')),
            ],
            options={
                'verbose_name_plural': 'プロフィール',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='プランタイトル')),
                ('description', models.TextField(max_length=255, verbose_name='プランの説明')),
                ('image', models.ImageField(default='', upload_to='', verbose_name='イメージ画像')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='料金')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('tags', models.ManyToManyField(blank=True, to='yorozu.Tag')),
                ('yorozuya_profile', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='yorozu.Profile', verbose_name='作成者')),
            ],
            options={
                'verbose_name_plural': 'プラン',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(max_length=10, verbose_name='メッセージ内容')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('sender_yorozu_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='yorozu.Profile', verbose_name='送信者')),
            ],
            options={
                'verbose_name_plural': 'メッセージ',
            },
        ),
    ]
