# Generated by Django 2.2.2 on 2020-05-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver_yorozy_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_yorozu_id',
        ),
    ]
