# Generated by Django 2.2.2 on 2020-05-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_yorozu_id',
            field=models.ForeignKey(blank=True, default='yozozo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='yorozu.Profile', verbose_name='受信者'),
        ),
    ]
