# Generated by Django 2.2.2 on 2020-04-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0002_plan_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name_plural': 'アカウント'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'タグ'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(default='', upload_to='media/', verbose_name='イメージ画像'),
        ),
    ]
