# Generated by Django 2.2.2 on 2020-05-06 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0002_auto_20200506_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日'),
        ),
    ]
