# Generated by Django 2.2.2 on 2020-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0003_auto_20200409_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='イメージ画像'),
        ),
    ]
