# Generated by Django 2.2.2 on 2020-05-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0003_auto_20200510_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='ログイン状態'),
        ),
    ]
