# Generated by Django 2.2.2 on 2020-05-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0003_message_sender_yorozu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_yorozy_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='yorozu.Profile', verbose_name='受信者'),
        ),
    ]
