# Generated by Django 2.2.2 on 2020-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0004_auto_20200511_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日'),
        ),
    ]
