# Generated by Django 2.2.2 on 2020-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0004_auto_20200410_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tags',
            field=models.ManyToManyField(blank=True, to='yorozu.Tag'),
        ),
    ]
