# Generated by Django 2.2.2 on 2020-05-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0005_plan_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日'),
        ),
    ]
