# Generated by Django 2.2.2 on 2020-04-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0005_auto_20200418_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='名称'),
        ),
    ]
