# Generated by Django 2.2.2 on 2020-04-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0006_auto_20200418_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10, verbose_name='ニックネーム')),
                ('profile_description', models.TextField(max_length=255, verbose_name='プロフィール説明')),
                ('review_score', models.IntegerField(verbose_name='レビュースコア')),
            ],
            options={
                'verbose_name_plural': 'プロフィール',
            },
        ),
    ]
