# Generated by Django 2.2.2 on 2020-05-12 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0006_profile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(verbose_name='レビュー内容')),
                ('review_score', models.IntegerField(verbose_name='評価点数')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('receiver_yorozu_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='review_receiver', to='yorozu.Profile', verbose_name='受信者(万屋)')),
                ('sender_yorozu_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='review_sender', to='yorozu.Profile', verbose_name='送信者(ユーザー)')),
            ],
            options={
                'verbose_name_plural': 'レビュー',
            },
        ),
    ]
