# Generated by Django 2.2.2 on 2020-04-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='', upload_to='', verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='yorozu.Tag'),
        ),
    ]
