# Generated by Django 2.2.2 on 2020-04-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0008_auto_20200425_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_account',
            field=models.CharField(default='', max_length=80, verbose_name='facebookのアカウント'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_account',
            field=models.CharField(default='', max_length=80, verbose_name='instagramのアカウント'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_account',
            field=models.CharField(default='', max_length=80, verbose_name='twitterのアカウント'),
        ),
    ]
