# Generated by Django 2.2.2 on 2020-04-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0009_auto_20200425_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='tags',
        ),
        migrations.AddField(
            model_name='plan',
            name='nickname',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='yorozu.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pl',
            field=models.CharField(default='', max_length=100, verbose_name='プランリスト'),
        ),
    ]
