# Generated by Django 2.2.2 on 2020-04-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0010_auto_20200425_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pl',
            new_name='plan_list',
        ),
    ]
