# Generated by Django 2.2.2 on 2020-04-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0011_auto_20200425_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='nickname',
        ),
    ]
