# Generated by Django 2.2.2 on 2020-04-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0012_remove_plan_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='plan_list',
            new_name='pan_list',
        ),
        migrations.AddField(
            model_name='plan',
            name='yorozuya_profile',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_list', to='yorozu.Profile'),
        ),
    ]
