# Generated by Django 2.2.2 on 2020-04-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0014_auto_20200425_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan_list',
        ),
    ]
