# Generated by Django 2.2.2 on 2020-04-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0015_remove_profile_plan_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
        migrations.AddField(
            model_name='plan',
            name='tags',
            field=models.ManyToManyField(blank=True, to='yorozu.Tag'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(max_length=255, verbose_name='プランの説明'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_account',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='facebookのアカウント'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_account',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='instagramのアカウント'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_account',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='twitterのアカウント'),
        ),
    ]
