# Generated by Django 2.2.2 on 2020-04-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0016_auto_20200426_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='yorozuya_profile',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='yorozu.Profile', verbose_name='作成者'),
        ),
    ]
