# Generated by Django 2.2.2 on 2020-04-29 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0017_auto_20200428_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='planList',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='yorozu.Plan', verbose_name='プランリスト'),
        ),
    ]
