# Generated by Django 2.2.2 on 2020-04-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0018_profile_planlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='yorozuya_profile',
        ),
    ]
