# Generated by Django 2.2.2 on 2020-04-29 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0019_remove_plan_yorozuya_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='yorozuya_profile',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='yorozu.Profile', verbose_name='作成者'),
        ),
    ]
