# Generated by Django 2.2.2 on 2020-04-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0020_plan_yorozuya_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='planList',
            new_name='plan_list',
        ),
    ]
