# Generated by Django 2.2.2 on 2020-04-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0022_auto_20200429_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='yorozuya_name',
            field=models.CharField(default='', max_length=10, verbose_name='万事屋'),
        ),
    ]
