# Generated by Django 2.2.2 on 2020-04-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0023_profile_yorozuya_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='yorozu_main_image',
            field=models.ImageField(default='', upload_to='', verbose_name='万屋メイン画像'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yorozuya_name',
            field=models.CharField(default='', max_length=10, verbose_name='万事屋の名前'),
        ),
    ]
