# Generated by Django 2.2.2 on 2020-04-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0024_auto_20200430_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='yorozuya_profile',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='yorozu.Plan', verbose_name='作成者'),
        ),
    ]
