# Generated by Django 2.2.2 on 2020-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0025_auto_20200430_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='yorozuya_profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_list',
            field=models.ManyToManyField(default='', null=True, to='yorozu.Plan', verbose_name='プランリスト'),
        ),
    ]
