# Generated by Django 2.2.2 on 2020-05-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0027_remove_profile_plan_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(max_length=10, verbose_name='メッセージ内容')),
                ('target_id', models.CharField(max_length=10, verbose_name='送り先のID')),
                ('source_id', models.CharField(max_length=10, verbose_name='送り手のID')),
            ],
        ),
    ]
